- import_playbook: main.yaml
- hosts: localhost
  tasks:
    - name: Install tools
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - phpstorm
        - slack
        - figma
        - microsoft-teams
      
    - name: Configure git user email
      copy:
          dest: "~/.gitconfig.local"
          content: |
            [user]
                email = b.schulze-baek@shopware.com
