- import_playbook: main.yaml
- hosts: localhost
  tasks:
    - name: Install private Tools
      community.general.homebrew_cask:
        name: '{{ item }}'
      ignore_errors: yes
      with_items:
        - webstorm
    
    - name: Configure git user email
      copy:
        dest: "~/.gitconfig.local"
        content: |
          [user]
              email = benedikt@schulze-baek.de
