#!/bin/bash

function workspace-finder() {
    local ROOT=~/development/
    local HARDCODED=(
        ~/.config/nvim
    )
    local TMP_DIRS=()

    for pathname in "${HARDCODED[@]}"; do
        if [ -e "$pathname" ]; then
            TMP_DIRS+=( "$pathname" )
        fi
    done

    while IFS=  read -r -d $'\0'; do
        TMP_DIRS+=("$(readlink -f $REPLY)")
    done < <(find $ROOT -maxdepth 1 -mindepth 1 -type d -print0)

    TMP_DIRS+=("${DIRS[@]}")

    IFS=$'\n' TMP_DIRS=($(sort <<<"${TMP_DIRS[*]}"))
    unset IFS

    local TARGET_DIR=$(printf '%s\n' "${TMP_DIRS[@]}" | fzf --preview 'ls -la --color=auto {}')

    [ $TARGET_DIR ] || return 0

    cd "${TARGET_DIR}"
}
